"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-bddi_@y0r7_3ma$^us%)##6953r37!53pnnojd(g7t$z+$+yu_')

# SECURITY WARNING: don't run with debug turned on in production!
# Use an environment variable so production is guaranteed False.
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

# Comma-separated hostnames in DJANGO_ALLOWED_HOSTS, e.g. "example.com,localhost"
ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'LibraryProject.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (user-uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# ============================================================================
# HTTPS AND SECURITY CONFIGURATION
# ============================================================================

# HTTPS Enforcement and HSTS (HTTP Strict-Transport-Security)
# These settings enforce secure HTTPS connections and prevent downgrade attacks
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
# SECURE_HSTS_SECONDS: Time in seconds browsers should only access the site via HTTPS
# Set to 31536000 (1 year) in production after testing
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
# Include all subdomains in the HSTS policy
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
# Allow the site to be preloaded in browsers' HSTS preload lists
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'

# ============================================================================
# SECURE COOKIES CONFIGURATION
# ============================================================================

# SESSION_COOKIE_SECURE: Ensure session cookies are only transmitted over HTTPS
# This prevents session hijacking over insecure HTTP connections
SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE: Ensure CSRF protection cookies are only transmitted over HTTPS
# This protects against cross-site request forgery attacks over insecure connections
CSRF_COOKIE_SECURE = True

# Additional cookie security settings
# Set SameSite attribute to prevent cookies from being sent in cross-site requests
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE = 'Strict'

# HttpOnly flag is automatically set for session cookies in Django
# This prevents JavaScript from accessing the session cookie

# ============================================================================
# SECURE HEADERS CONFIGURATION
# ============================================================================

# X_FRAME_OPTIONS: Prevent clickjacking attacks by denying the site from being framed
# Options: 'DENY', 'SAMEORIGIN', or 'ALLOW-FROM origin'
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevent browsers from MIME-sniffing responses
# This protects against MIME-sniffing attacks by forcing the browser to respect content-type headers
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Enable the browser's built-in XSS protection filter
# This helps prevent reflected cross-site scripting (XSS) attacks
SECURE_BROWSER_XSS_FILTER = True

# SECURE_REFERRER_POLICY: Control how much referrer information is shared
# 'strict-origin-when-cross-origin' prevents exposing full URLs to other sites
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Content Security Policy (simple default; adjust per deployment needs)
CONTENT_SECURITY_POLICY = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self';"

# Allow overriding with trusted origins (comma-separated) for CSRF on HTTPS endpoints
csrf_trusted = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin for origin in csrf_trusted.split(',') if origin]
