# Generated by Django 6.0.1 on 2026-02-13 23:30

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        # First, remove the old tags field
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        # Then delete the Tag model
        migrations.DeleteModel(
            name='Tag',
        ),
        # Finally, add the new TaggableManager field
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
